apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: mariadb-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      terminationGracePeriodSeconds: 10
      volumeClaimTemplates:
        - metadata:
            name: mysql-storage
          spec:
            accessModes:
              - ReadWriteMany
            storageClassName: nfs-csi
            resources:
              requests:
                storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type:
    ClusterIP: None