apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deployment
  namespace: sinan-ns
  labels:
    app: fitness-app
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
      - name: fitness-app-container
        image: muralisocial123/kyndrl-flower-app:v1.1.0
        ports:
        - containerPort: 3015