apiVersion: v1
kind: Pod
metadata:
  name: portfolio-pod
  namespace: sinan-ns
  labels:
    app: portfolio
spec:
  containers:
    - name: portfolio-container
      image: muhammedsinanust/portfolio:latest
      ports:
        - containerPort: 80