apiVersion: apps/v1
kind: Deployment
metadata:
  name: duni-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: duni
  template:
    metadata:
      labels:
        app: duni
    spec:
      containers:
        - name: duni-container
          image: muhammedsinanust/duniversity:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: mariadb-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: duni-service
spec:
  selector:
    app: duni
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP