apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Root@123
  MYSQL_USER: college_user
  MYSQL_PASSWORD: deereddy@123
  MYSQL_DATABASE: grievance_db