apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.31.1.190
  share: /var/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
